# Generated by Django 5.2.5 on 2025-09-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_favourite_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='pic',
            field=models.CharField(default='no_picture.jpg', help_text='Filename of the favourite recipe image in static/recipes/images/', max_length=100),
        ),
    ]
