# Generated by Django 5.2.5 on 2025-09-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='pic',
            field=models.ImageField(default='no_picture.jpg', upload_to='favourites'),
        ),
    ]
