# Generated by Django 5.2.5 on 2025-09-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, help_text='Short description of the recipe')),
                ('instructions', models.TextField(blank=True, help_text='Step-by-step cooking instructions')),
                ('ingredients', models.TextField(help_text='Comma-separated list of ingredients')),
                ('cooking_time', models.PositiveIntegerField(help_text='Cooking time in minutes')),
                ('difficulty', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
